# Generated by Django 4.2.1 on 2023-05-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
